#!/usr/bin/env bash

VERSION_FILE=$(__get_version_file)
VERSION_PREFIX=$(git config --get gitflow.prefix.versiontag)
VERSION_FILE2="$ROOT_DIR/*/_version.py"

if [ ! -z "$VERSION_PREFIX" ]; then
    VERSION=${VERSION#$VERSION_PREFIX}
fi

echo -n "$VERSION" > $VERSION_FILE && \
    echo "# Autogenerated via git flow." > $VERSION_FILE2 && \
    echo "__version__ = '$VERSION'" >> $VERSION_FILE2 && \
    git add $VERSION_FILE $VERSION_FILE2 && \
    git commit -m "Bumped version to $VERSION"

if [ $? -ne 0 ]; then
    __print_fail "Unable to write version to $VERSION_FILE."
    return 1
else
    return 0
fi
